// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRd1opXILkusJwgu1VKPoj1gVUHP6dBho',
    appId: '1:529017755873:android:7a39d6d3b8e6b6cab17fa0',
    messagingSenderId: '529017755873',
    projectId: 'octagon-f9c20',
    storageBucket: 'octagon-f9c20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ1qgexmtrytsBGzF_yrH-k7Q22jC21yM',
    appId: '1:529017755873:ios:36224634ed74baf5b17fa0',
    messagingSenderId: '529017755873',
    projectId: 'octagon-f9c20',
    storageBucket: 'octagon-f9c20.firebasestorage.app',
    androidClientId: '529017755873-csu193p0gksrj3gdkbaf95itp6rk2hut.apps.googleusercontent.com',
    iosClientId: '529017755873-3o33f6r6kl5n747o67h67fbflpbmpnke.apps.googleusercontent.com',
    iosBundleId: 'com.octagon.app',
  );

}